using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    /// <inheritdoc />
    public partial class AddQuickMeasures : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""QuickMeasures"" (
                    ""QuickMeasureId"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""QuestionId"" integer NULL,
                    ""CategoryId"" integer NULL,
                    ""ScoreThreshold"" integer NOT NULL,
                    ""IsExclusive"" boolean NOT NULL,
                    ""Priority"" integer NOT NULL,
                    ""TriggerType"" text NOT NULL,
                    ""RequiredOption"" integer NULL,
                    ""RequiredText"" text NULL,
                    ""RequiredValue"" numeric NULL,
                    ""Operator"" text NULL,
                    ""FallbackText"" text NOT NULL,
                    ""Title"" text NULL,
                    ""ResourceUrl"" text NULL,
                    CONSTRAINT ""PK_QuickMeasures"" PRIMARY KEY (""QuickMeasureId""),
                    CONSTRAINT ""FK_QuickMeasures_Categories_CategoryId"" FOREIGN KEY (""CategoryId"")
                        REFERENCES ""Categories"" (""CategoryId"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_QuickMeasures_QuestionOptions_RequiredOption"" FOREIGN KEY (""RequiredOption"")
                        REFERENCES ""QuestionOptions"" (""QuestionOptionId"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_QuickMeasures_Questions_QuestionId"" FOREIGN KEY (""QuestionId"")
                        REFERENCES ""Questions"" (""QuestionId"") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS ""IX_QuickMeasures_CategoryId""
                    ON ""QuickMeasures"" (""CategoryId"");

                CREATE INDEX IF NOT EXISTS ""IX_QuickMeasures_QuestionId""
                    ON ""QuickMeasures"" (""QuestionId"");

                CREATE INDEX IF NOT EXISTS ""IX_QuickMeasures_RequiredOption""
                    ON ""QuickMeasures"" (""RequiredOption"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "QuickMeasures");
        }
    }
}
