// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.src.Infrastructure.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311114040_AddSeverityModel")]
    partial class AddSeverityModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.src.Domain.Models.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Measure", b =>
                {
                    b.Property<int>("MeasureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeasureId"));

                    b.Property<string>("FallbackText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int?>("RequiredOption")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredText")
                        .HasColumnType("text");

                    b.Property<decimal?>("RequiredValue")
                        .HasColumnType("numeric");

                    b.HasKey("MeasureId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("RequiredOption");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("backend.src.Domain.Models.MeasureText", b =>
                {
                    b.Property<int>("MeasureId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MeasureId", "LanguageCode");

                    b.HasIndex("LanguageCode");

                    b.ToTable("MeasureTexts");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Measurement", b =>
                {
                    b.Property<int>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeasurementId"));

                    b.Property<string>("FallbackText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MeasurementId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("backend.src.Domain.Models.MeasurementResult", b =>
                {
                    b.Property<int>("MeasurementId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RegisteredBy")
                        .HasColumnType("integer");

                    b.Property<decimal>("Result")
                        .HasColumnType("numeric");

                    b.HasKey("MeasurementId", "PatientId", "RegisteredAt");

                    b.HasIndex("PatientId");

                    b.HasIndex("RegisteredBy");

                    b.ToTable("MeasurementResults");
                });

            modelBuilder.Entity("backend.src.Domain.Models.MeasurementText", b =>
                {
                    b.Property<int>("MeasurementId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MeasurementId", "LanguageCode");

                    b.HasIndex("LanguageCode");

                    b.ToTable("MeasurementTexts");
                });

            modelBuilder.Entity("backend.src.Domain.Models.OptionText", b =>
                {
                    b.Property<int>("QuestionOptionId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QuestionOptionId", "LanguageCode");

                    b.HasIndex("LanguageCode");

                    b.ToTable("OptionTexts");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("backend.src.Domain.Models.PatientAccess", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("integer");

                    b.HasKey("PatientId", "PersonnelId");

                    b.HasIndex("PersonnelId");

                    b.ToTable("PatientAccesses");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("backend.src.Domain.Models.QueryQuestion", b =>
                {
                    b.Property<int>("QueryId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.HasKey("QueryId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QueryQuestions");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("FallbackText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredRole")
                        .HasColumnType("text");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("backend.src.Domain.Models.QuestionDependency", b =>
                {
                    b.Property<int>("ParentQueryId")
                        .HasColumnType("integer");

                    b.Property<int>("ParentQuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("ChildQueryId")
                        .HasColumnType("integer");

                    b.Property<int>("ChildQuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TriggerNumberValue")
                        .HasColumnType("numeric");

                    b.Property<int?>("TriggerOptionId")
                        .HasColumnType("integer");

                    b.Property<string>("TriggerTextValue")
                        .HasColumnType("text");

                    b.HasKey("ParentQueryId", "ParentQuestionId", "ChildQueryId", "ChildQuestionId");

                    b.HasIndex("ChildQueryId");

                    b.HasIndex("ChildQuestionId");

                    b.HasIndex("ParentQuestionId");

                    b.HasIndex("TriggerOptionId");

                    b.ToTable("QuestionDependencies");
                });

            modelBuilder.Entity("backend.src.Domain.Models.QuestionOption", b =>
                {
                    b.Property<int>("QuestionOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionOptionId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FallbackText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("QuestionOptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("backend.src.Domain.Models.QuestionText", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("QuestionId", "LanguageCode");

                    b.HasIndex("LanguageCode");

                    b.ToTable("QuestionTexts");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Response", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("NumberValue")
                        .HasColumnType("numeric");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("integer");

                    b.Property<string>("TextValue")
                        .HasColumnType("text");

                    b.HasKey("PatientId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Severity", b =>
                {
                    b.Property<int>("SeverityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeverityId"));

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int?>("RequiredOption")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredText")
                        .HasColumnType("text");

                    b.Property<decimal?>("RequiredValue")
                        .HasColumnType("numeric");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("SeverityId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("RequiredOption");

                    b.ToTable("Severities");
                });

            modelBuilder.Entity("backend.src.Domain.Models.ToDo", b =>
                {
                    b.Property<int>("ToDoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ToDoId"));

                    b.Property<bool>("Finished")
                        .HasColumnType("boolean");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("integer");

                    b.Property<bool>("Public")
                        .HasColumnType("boolean");

                    b.Property<string>("ToDoText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ToDoId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PersonnelId");

                    b.ToTable("ToDos");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Measure", b =>
                {
                    b.HasOne("backend.src.Domain.Models.Question", "Question")
                        .WithMany("Measures")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.QuestionOption", "RequiredOptionNavigation")
                        .WithMany()
                        .HasForeignKey("RequiredOption")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Question");

                    b.Navigation("RequiredOptionNavigation");
                });

            modelBuilder.Entity("backend.src.Domain.Models.MeasureText", b =>
                {
                    b.HasOne("backend.src.Domain.Models.Language", "Language")
                        .WithMany("MeasureTexts")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.Measure", "Measure")
                        .WithMany("Texts")
                        .HasForeignKey("MeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Measure");
                });

            modelBuilder.Entity("backend.src.Domain.Models.MeasurementResult", b =>
                {
                    b.HasOne("backend.src.Domain.Models.Measurement", "Measurement")
                        .WithMany("Results")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.Patient", "Patient")
                        .WithMany("MeasurementResults")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.Personnel", "RegisteredByPersonnel")
                        .WithMany("RegisteredMeasurementResults")
                        .HasForeignKey("RegisteredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Measurement");

                    b.Navigation("Patient");

                    b.Navigation("RegisteredByPersonnel");
                });

            modelBuilder.Entity("backend.src.Domain.Models.MeasurementText", b =>
                {
                    b.HasOne("backend.src.Domain.Models.Language", "Language")
                        .WithMany("MeasurementTexts")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.Measurement", "Measurement")
                        .WithMany("Texts")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("backend.src.Domain.Models.OptionText", b =>
                {
                    b.HasOne("backend.src.Domain.Models.Language", "Language")
                        .WithMany("OptionTexts")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.QuestionOption", "Option")
                        .WithMany("Texts")
                        .HasForeignKey("QuestionOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("backend.src.Domain.Models.PatientAccess", b =>
                {
                    b.HasOne("backend.src.Domain.Models.Patient", "Patient")
                        .WithMany("PatientAccesses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.Personnel", "Personnel")
                        .WithMany("PatientAccesses")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("backend.src.Domain.Models.QueryQuestion", b =>
                {
                    b.HasOne("backend.src.Domain.Models.Query", "Query")
                        .WithMany("QueryQuestions")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.Question", "Question")
                        .WithMany("QueryQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("backend.src.Domain.Models.QuestionDependency", b =>
                {
                    b.HasOne("backend.src.Domain.Models.Query", "ChildQuery")
                        .WithMany("ChildDependencies")
                        .HasForeignKey("ChildQueryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.Question", "ChildQuestion")
                        .WithMany("ChildDependencies")
                        .HasForeignKey("ChildQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.Query", "ParentQuery")
                        .WithMany("ParentDependencies")
                        .HasForeignKey("ParentQueryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.Question", "ParentQuestion")
                        .WithMany("ParentDependencies")
                        .HasForeignKey("ParentQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.QuestionOption", "TriggerOption")
                        .WithMany()
                        .HasForeignKey("TriggerOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChildQuery");

                    b.Navigation("ChildQuestion");

                    b.Navigation("ParentQuery");

                    b.Navigation("ParentQuestion");

                    b.Navigation("TriggerOption");
                });

            modelBuilder.Entity("backend.src.Domain.Models.QuestionOption", b =>
                {
                    b.HasOne("backend.src.Domain.Models.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("backend.src.Domain.Models.QuestionText", b =>
                {
                    b.HasOne("backend.src.Domain.Models.Language", "Language")
                        .WithMany("QuestionTexts")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.Question", "Question")
                        .WithMany("Texts")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Response", b =>
                {
                    b.HasOne("backend.src.Domain.Models.Patient", "Patient")
                        .WithMany("Responses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.Question", "Question")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.QuestionOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Patient");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Severity", b =>
                {
                    b.HasOne("backend.src.Domain.Models.Question", "Question")
                        .WithMany("Severities")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.QuestionOption", "RequiredOptionNavigation")
                        .WithMany()
                        .HasForeignKey("RequiredOption")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Question");

                    b.Navigation("RequiredOptionNavigation");
                });

            modelBuilder.Entity("backend.src.Domain.Models.ToDo", b =>
                {
                    b.HasOne("backend.src.Domain.Models.Patient", "Patient")
                        .WithMany("ToDos")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.src.Domain.Models.Personnel", "Personnel")
                        .WithMany("ToDos")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Language", b =>
                {
                    b.Navigation("MeasureTexts");

                    b.Navigation("MeasurementTexts");

                    b.Navigation("OptionTexts");

                    b.Navigation("QuestionTexts");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Measure", b =>
                {
                    b.Navigation("Texts");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Measurement", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("Texts");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Patient", b =>
                {
                    b.Navigation("MeasurementResults");

                    b.Navigation("PatientAccesses");

                    b.Navigation("Responses");

                    b.Navigation("ToDos");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Personnel", b =>
                {
                    b.Navigation("PatientAccesses");

                    b.Navigation("RegisteredMeasurementResults");

                    b.Navigation("ToDos");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Query", b =>
                {
                    b.Navigation("ChildDependencies");

                    b.Navigation("ParentDependencies");

                    b.Navigation("QueryQuestions");
                });

            modelBuilder.Entity("backend.src.Domain.Models.Question", b =>
                {
                    b.Navigation("ChildDependencies");

                    b.Navigation("Measures");

                    b.Navigation("Options");

                    b.Navigation("ParentDependencies");

                    b.Navigation("QueryQuestions");

                    b.Navigation("Responses");

                    b.Navigation("Severities");

                    b.Navigation("Texts");
                });

            modelBuilder.Entity("backend.src.Domain.Models.QuestionOption", b =>
                {
                    b.Navigation("Texts");
                });
#pragma warning restore 612, 618
        }
    }
}
